#!/bin/bash
# 🎯 Comandos de Heroku - Copia y Pega
# Guía rápida de comandos más usados

echo "🚀 COMANDOS DE HEROKU - MASTER PLAN"
echo "===================================="
echo ""

# INSTALACIÓN Y SETUP
echo "📦 INSTALACIÓN Y SETUP"
echo "----------------------"
echo "# Instalar Heroku CLI (Linux/Mac)"
echo "curl https://cli-assets.heroku.com/install.sh | sh"
echo ""
echo "# Login"
echo "heroku login"
echo ""
echo "# Crear app con nombre automático"
echo "heroku create"
echo ""
echo "# Crear app con nombre específico"
echo "heroku create masterplan-produccion"
echo ""

# DESPLIEGUE
echo "🚀 DESPLIEGUE"
echo "-------------"
echo "# Primera vez"
echo "git add ."
echo "git commit -m 'Initial deploy'"
echo "git push heroku main"
echo ""
echo "# Actualizaciones posteriores"
echo "git add ."
echo "git commit -m 'Update: descripción del cambio'"
echo "git push heroku main"
echo ""

# MONITOREO
echo "📊 MONITOREO"
echo "------------"
echo "# Ver logs en tiempo real"
echo "heroku logs --tail"
echo ""
echo "# Ver últimos 100 logs"
echo "heroku logs -n 100"
echo ""
echo "# Ver logs con filtro"
echo "heroku logs --source app --tail"
echo ""
echo "# Estado de la app"
echo "heroku ps"
echo ""
echo "# Información de la app"
echo "heroku info"
echo ""

# GESTIÓN
echo "🔧 GESTIÓN"
echo "----------"
echo "# Abrir la app en navegador"
echo "heroku open"
echo ""
echo "# Reiniciar la app"
echo "heroku restart"
echo ""
echo "# Escalar dynos"
echo "heroku ps:scale web=1"
echo ""
echo "# Ver variables de entorno"
echo "heroku config"
echo ""
echo "# Agregar variable de entorno"
echo "heroku config:set CLAVE=valor"
echo ""
echo "# Eliminar variable de entorno"
echo "heroku config:unset CLAVE"
echo ""

# DEBUGGING
echo "🐛 DEBUGGING"
echo "------------"
echo "# Ejecutar bash en Heroku"
echo "heroku run bash"
echo ""
echo "# Ver build logs"
echo "heroku builds:output"
echo ""
echo "# Limpiar cache"
echo "heroku plugins:install heroku-repo"
echo "heroku repo:purge_cache -a nombre-app"
echo ""

# BASE DE DATOS (futuro)
echo "💾 BASE DE DATOS (para futuro)"
echo "------------------------------"
echo "# Agregar Postgres"
echo "heroku addons:create heroku-postgresql:mini"
echo ""
echo "# Ver base de datos"
echo "heroku pg:info"
echo ""
echo "# Backup"
echo "heroku pg:backups:capture"
echo ""

# DOMINIOS
echo "🌐 DOMINIOS"
echo "-----------"
echo "# Ver dominios"
echo "heroku domains"
echo ""
echo "# Agregar dominio personalizado"
echo "heroku domains:add www.tudominio.com"
echo ""

# COLABORADORES
echo "👥 COLABORADORES"
echo "----------------"
echo "# Ver colaboradores"
echo "heroku access"
echo ""
echo "# Agregar colaborador"
echo "heroku access:add usuario@email.com"
echo ""

# MANTENIMIENTO
echo "🔨 MANTENIMIENTO"
echo "----------------"
echo "# Activar modo mantenimiento"
echo "heroku maintenance:on"
echo ""
echo "# Desactivar modo mantenimiento"
echo "heroku maintenance:off"
echo ""

# SCRIPTS PERSONALIZADOS
echo "⚡ SCRIPTS PERSONALIZADOS (este proyecto)"
echo "----------------------------------------"
echo "# Probar localmente (modo producción)"
echo "./test-production.sh"
echo ""
echo "# Deploy automático"
echo "./deploy.sh"
echo ""

echo ""
echo "✨ TIP: Guarda estos comandos o ejecuta:"
echo "   cat heroku-commands.sh | less"
echo ""
echo "📖 Documentación completa: HEROKU-DEPLOYMENT-GUIDE.md"
echo ""
